### ISSUE TITLE
Implement the OCR-worker service

### ISSUE THREAD

**Issue by BerniUtz** [BerniUtz/WS23-SWKOM#38]
to...

- [x] retrieve messages from the queue (sent by REST-Server on document-upload),
- [x] fetch the original PDF-document from MinIO
- [x] Perform the OCR-recognition
- [x] Store the text-result in PostgreSQL
- [x] Show functionallity with unit-tests

**Comment by leonardstruck** [comment]
#48 / #49 

Meiner Meinung nach bedarf es weiterer Entwicklungsarbeit, da der Service momentan die Warteschlange nur einmalig beim Starten ausliest. Anschließend stoppt er oder stürzt ab, falls die Warteschlange leer ist. Eine Implementierung als dauerhaft laufender Dienst wäre daher noch notwendig.

**Comment by SirPoz** [comment]
Ja ist nur mal die Basis Funktionalität. Hab auch im Code 2 Todos vermerkt die wir dann besprechen sollten. 

Es sollte eigentlich der IqueueService irgendeine Art von Subscribemöglichkeit haben.

**Comment by SirPoz** [comment]
Gibt es schon eine subscribe-Möglichkeit zum IqueueService? Ansonsten schaue ich mir das auch gleich an
