### ISSUE TITLE
A webserver service paperlessNGX webpages integrated

### ISSUE THREAD

**Issue by BerniUtz** [BerniUtz/WS23-SWKOM#7]

**Comment by leonardstruck** [comment]
Versteh nicht ganz was heißen soll.. In dem PR #12 ist der Webserver integriert mitsamt dem frontend... Ist das vielleicht dann schon damit erledigt?

**Comment by leonardstruck** [comment]
@BerniUtz kannst du da nochmal kurz erläutern was mit dem issue genau gemeint ist?

**Comment by BerniUtz** [comment]
Ich hab da damals nur die Punkte von den Angaben raus kopiert. Aber ich kann dann wenn ich von der Arbeit daheim bin nochmal rein schauen ob eine genauere Beschreibung steht

**Comment by BerniUtz** [comment]
https://moodle.technikum-wien.at/pluginfile.php/2041226/mod_resource/content/1/BIF5-SWKOM_Project.pdf

Da hab ich das her @leonardstruck also schon gut möglich dass das damit schon erledigt ist

**Comment by leonardstruck** [comment]
Ah, danke 👍
