### ISSUE TITLE
paperlessNGX communicates with REST server

### ISSUE THREAD

**Issue by BerniUtz** [BerniUtz/WS23-SWKOM#8]

**Comment by SirPoz** [comment]
Kommunikation zwischen paperlessNGX und REST ist ja gegeben sobald der REST server läuft. So wie ich das gesehen habe ist die api funktionalität in paperlessNGX ja komplett integriert. Da muss in der Angular anwendung selbst nichts mehr verändert werden

**Comment by leonardstruck** [comment]
Die Angular App müssen wir eh nicht anrühren. Denke dass wir das ebenfalls schließen können.
